### ISSUE TITLE
Compiling issue : Parameter 'event' implicitly has an 'any' type

### ISSUE THREAD

**Issue by skysrc** [achwilko/ngx-inactivity#3]
![implicit-type](https://user-images.githubusercontent.com/13814845/36469279-a8985704-1721-11e8-928a-5b493bd2aa32.png)

Unable to compile 
@angular/cli: 1.4.9,
Angular : 4.4.6

**Comment by JaniBasha1** [comment]
Is this resolved? I am getting same error?

**Comment by achwilko** [comment]
Hi @JaniBasha1 

Unfortunately, **above issue is still valid**. I will try to update the pacakge to the newest Angular version as soon as I find time to work on it. Any help / pull request is welcome :)

**Comment by JaniBasha1** [comment]
I resolved it locally... I can fork  a  pull request if you want me to do so..

**Comment by achwilko** [comment]
@JaniBasha1 that would be helpful, feel free to do it

**Comment by JaniBasha1** [comment]
Hi @achwilko , Please complete the PR

**Comment by achwilko** [comment]
Sure, I've just reviewed and merged. Thanks for your contribution.
