### ISSUE TITLE
Event implicitly has type any error

### ISSUE THREAD

**Issue by JaniBasha1** [achwilko/ngx-inactivity#4]
Hi Team,
There is event used in ngx inactivity directive.ts which is of type any. I am getting error over there. Can this be solved by adding any all 3 event emitters or any other alternative. Pls suggest.

**Comment by achwilko** [comment]
Hi @JaniBasha1 

As I mentioned in other issues, I will try to update the package to the newest Angular version as soon as I find time to work on it. Any help / suggestion / pull request is welcome :)
