### ISSUE TITLE
How to configure events for inactivity

### ISSUE THREAD

**Issue by prashantpimpale93** [achwilko/ngx-inactivity#7]
First of all thank @achwilko for the library.

Question:
Can I configure events like 

> mouseover

 event should be disable and 

> click

 event should be enable.

Is it possible or already have a feature like this?

**Comment by achwilko** [comment]
Hi @prashantpimpale93 unfortunately, this can't be configured but any pull requests are welcome!

**Comment by prashantpimpale93** [comment]
@achwilko Can you point me towards Contribution Document or Guide?
